spring:
  datasource:
    username: sa
    password: Zx20180607
    url: jdbc:sqlserver://localhost:1433;database=DiamondDocs
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 100MB
  mail:
    username: diamond_docs@163.com
    password: SROYYIQXDOANMRTC
    host: smtp.163.com
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
    port: 465
mybatis:
  type-aliases-package: com.diamond.pojo,com.diamond.dto
  mapper-locations: classpath:mapper/*.xml